### PR TITLE
Update Task.h

### PR DESCRIPTION
**Pull request by Chris685**
Fixing Issue after Updating to ESP Arduino Version 3.1.0 https://github.com/nrwiersma/ESP8266Scheduler/issues/38

### CODE REVIEW

**Comment by nrwiersma** [comment]
It looks like you need to update the build flags in the platform.ini to change the framework version.

**Comment by nrwiersma** [comment]
Specifically you need to add this at the end of [env:nodemcuv2]:
```ini
; this should be replaced with the correct platform version once espressif8266 has caught up.
platform_packages =
    framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git
    toolchain-xtensa@~2.100300.210717
```
Which fails based on `cont_yield` for the current version.

**Comment by Chris685** [comment]
Sorry, i dont understand this problem :(

**Comment by Chris685** [comment]
Got it now, This was not as easy for me - thanks for your support - i try to learn to work with Github more and more :)

**Review by nrwiersma — APPROVED** [review]
LGTM 🎉

**Pull request merged**
